WELLCOME: .db CS, CR, CR, LF,"Z80 Mini Iniciado", CR, LF, 00H
MSG_MONITOR .db "Z80 MINI, H TO HELP",CR, 00H

MSG_MENU0  .db "F1 RUN (JP $8000)",CR, 00H
MSG_MENU1  .db "F2 Intel hex loader",CR, 00H
MSG_MENU2  .db "B - Basic",CR, 00H
MSG_MENU3  .db "D AAAA - DISPLAY",CR,00H
MSG_MENU4  .db "M AAAA - MODIFY",CR,00H
MSG_MENU5  .db "G AAAA - GO TO",CR, 00H
MSG_MENU6  .db "O Out AA DD",CR, 00H
MSG_MENU7  .db "I In AA",CR, 00H
MSG_MENU8  .db "1 I2C Scan",CR, 00H
MSG_MENU9  .db "2 I2C PC -> MEM",CR, 00H
MSG_MENU10 .db "3 I2C MEM -> PC",CR, 00H
MSG_MENU11 .db "4 I2C WRITE DD",CR, 00H
MSG_MENU12 .db "5 I2C WRITE RR DD",CR, 00H
MSG_MENU13 .db "6 I2C READ ONE BYTE",CR, 00H
MSG_MENU14 .db "7 I2C READ RR BYTE", CR, 00H 
MSG_MENU15 .db "8 Read Memory", 00H ; ultimo não tem CR (nova linha)

MSG_MENU_CONTINUE .db "CONTINUE...", 00H


MSG_READFILE_EXE .db "_EXE", 00H
MSG_READFILE_IMG .db "_IMG", 00H
MSG_READFILE_TXT .db "_TXT", 00H

LISTMsg:    .DB  CS,"I2C device found at:",CR,0
MSG_MEM2CPU .db CS,"COPY I2C MEM TO CPU",CR, 00H
MSG_CPU2MEM .db CS,"COPY CPU TO I2C MEM",CR, 00H

MSG_I2C_WR_DD    .db CS,"WRITE ONE BYTE",CR, 00H
MSG_I2C_WR_RR_DD .db CS,"WRITE REG ONE BYTE",CR, 00H
MSG_I2C_RD       .db CS,"READ ONE BYTE",CR, 00H
MSG_I2C_RD_RR    .db CS,"READ REG ONE BYTE",CR, 00H

MSG_FROM    .db "FROM: ", 00H
MSG_TO      .db CR,"TO: ", 00H
MSG_SIZE    .db CR,"SIZE(BYTES): ", 00H
MSG_COPYOK  .db CR,"COPY OK", 00H
MSG_COPYFAIL  .db CR,"COPY FAIL", 00H

MSG_DEV_ADDR  .db CR,"DEVICE ADDR(AA): ", 00H
MSG_DEV_REG   .db CR,"REGISTER(RR): ", 00H
MSG_DEV_DATA  .db CR,"DATA(DD): ", 00H

MSG_BASIC .db "(C)old or (w)arm ?",CR, 00H

MSG_ILOAD .db $0C, "Intel HEX loader...", CR, 00H
FILEOK    .DB      "FILE RECEIVED OK",CR,00H
CSUMERR   .DB    "CHECKSUM ERROR",CR,00H