SHOW_MENU:
    LD A, CR
    CALL SEND_CHAR_TO_GLCD

    LD DE, MSG_MENU0
    LD A, 0
    CALL SEND_STRING_TO_GLCD

    LD DE, MSG_MENU1
    LD A, 0
    CALL SEND_STRING_TO_GLCD

    LD DE, MSG_MENU2
    LD A, 0
    CALL SEND_STRING_TO_GLCD

    LD DE, MSG_MENU3
    LD A, 0
    CALL SEND_STRING_TO_GLCD

    LD DE, MSG_MENU4
    LD A, 0
    CALL SEND_STRING_TO_GLCD


    LD DE, MSG_MENU8
    LD A, 0
    CALL SEND_STRING_TO_GLCD

    LD DE, MSG_MENU9
    LD A, 0
    CALL SEND_STRING_TO_GLCD

    LD DE, MSG_MENU10
    LD A, 0
    CALL SEND_STRING_TO_GLCD

    LD DE, MSG_MENU11
    LD A, 0
    CALL SEND_STRING_TO_GLCD

    LD DE, MSG_MENU12
    LD A, 0
    CALL SEND_STRING_TO_GLCD

    LD DE, MSG_MENU13
    LD A, 0
    CALL SEND_STRING_TO_GLCD

    LD DE, MSG_MENU14
    LD A, 0
    CALL SEND_STRING_TO_GLCD

    LD DE, MSG_MENU15
    LD A, 0
    CALL SEND_STRING_TO_GLCD

    LD DE, MSG_MENU16
    LD A, 0
    CALL SEND_STRING_TO_GLCD

    LD DE, MSG_MENU17
    LD A, 0
    CALL SEND_STRING_TO_GLCD

    LD DE, MSG_MENU18
    LD A, 0
    CALL SEND_STRING_TO_GLCD

    LD DE, MSG_MENU19
    LD A, 0
    CALL SEND_STRING_TO_GLCD

    LD DE, MSG_MENU20
    LD A, 0
    CALL SEND_STRING_TO_GLCD

    LD DE, MSG_MENU21
    LD A, 0
    CALL SEND_STRING_TO_GLCD



    RET